version: '3.8'

services:
  # kong-db:
  #   image: postgres:11
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - kong-db-data:/var/lib/postgresql/data
  #     - ./init-konga-db.sh:/docker-entrypoint-initdb.d/init-konga-db.sh
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-U", "kong"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

  mysql-db-1:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-mysql.sql:/docker-entrypoint-initdb.d/init-mysql.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  # kong:
  #   image: kong/kong-gateway:3.6
  #   depends_on:
  #     kong-db:
  #       condition: service_healthy
  #   environment:
  #     KONG_DATABASE: postgres
  #     KONG_PG_HOST: kong-db
  #     KONG_PG_USER: kong
  #     KONG_PG_PASSWORD: kong
  #     KONG_PROXY_ACCESS_LOG: /dev/stdout
  #     KONG_ADMIN_ACCESS_LOG: /dev/stdout
  #     KONG_PROXY_ERROR_LOG: /dev/stderr
  #     KONG_ADMIN_ERROR_LOG: /dev/stderr
  #     KONG_ADMIN_LISTEN: 0.0.0.0:8001
  #   command: >
  #     sh -c "
  #       kong migrations bootstrap &&
  #       kong start
  #     "
  #   ports:
  #     - "8000:8000"
  #     - "8001:8001"

volumes:
  # kong-db-data:
  mysql-data:
